services:
  # 1. Engine PHP 8.3
  app:
    container_name: app-siskha-store
    image: php:8.3-fpm
    volumes:
      - .:/var/www/html
    command: sh -c "docker-php-ext-install pdo_mysql && php-fpm"
    networks:
      - siskha-store-network
      - web-gateway

  # 2. Web Server Nginx
  web-siskha:
    container_name: web-siskha-store
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - siskha-store-network
      - web-gateway

  # 3. Database MySQL
  db:
    container_name: db-siskha-store
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=siskha_store
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=yazid
      - MYSQL_PASSWORD=secret
    volumes:
      - db-data-siskha-store:/var/lib/mysql
    networks:
      - siskha-store-network

  # 4. phpMyAdmin (Opsional, akses via Proxy nanti)
  phpmyadmin:
    container_name: pma-siskha-store
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - siskha-store-network
      - web-gateway

networks:
  # Network internal khusus proyek ini
  siskha-store-network:
    driver: bridge
  # Network eksternal untuk komunikasi ke Nginx Proxy Manager
  web-gateway:
    external: true

volumes:
  db-data-siskha-store: